### ISSUE TITLE
[Request] Adding option between user PATH and system PATH

### ISSUE THREAD

**Issue by GitesHubisz** [HorridModz/Flow.Launcher.Plugin.Add2Path#1]
Hey.

I would like to ask you if there is a chance to be able to select the option to choose between system PATH and user PATH.

Thanks in advance, thanks for creating this plugin.

**Comment by HorridModz** [comment]
@GitesHubisz Yay, glad to hear someone uses my plugin! The program works by modifying the registry key `HKCU\Environment\Path`, as you can see [here](HKCU\\Environment). I just found this on StackOverflow xD, but I will look into the **user** path as well! Thanks for the suggestion.

**Comment by HorridModz** [comment]
Hmm, looks like `HKCU\Environment\Path` is for system and `HKEY_CURRENT_USER\Environment\Path` is for user. Makes sense; should be pretty easy to add when I get to it!
I guess user path will be default, and system will  have to be explicitly provided

**Comment by HorridModz** [comment]
Oops, wrong one lol! The above two registry keys are the same exact thing; what I really want is `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment`. Phew!

**Comment by HorridModz** [comment]
@GitesHubisz Haha, it's been over a month. But, contrary to your (either probable or indifferent) belief, I _have_ been hard at work on this! I've been doing a **bunch** of reworking and made improvements such as input validation and result filtering. And the feature to add to system path is working very well!
I don't mean to jinx it, but I should be done soon. I've been working on it a lot since it's summer and I have done everything I've been wanting to do. All that's left is to test it (and inevitably find more issues ;) )!

I'm probably talking to a wall here because I doubt anyone gives two shits (I can see that you give one, but probably not a full two) about my silly little plugin. But there.

**Comment by HorridModz** [comment]
@GitesHubisz The update is out, [Version 2.0](https://github.com/HorridModz/Flow.Launcher.Plugin.Add2Path/releases/tag/v2.0.0). You can run `pm update add2path` in FlowLauncher to update it.
